object Plugins {
    const val AndroidApplication = "com.android.application"
    const val KotlinAndroid = "org.jetbrains.kotlin.android"
    const val KotlinKapt = "kotlin-kapt"
    const val KotlinParcelize = "kotlin-parcelize"
    const val AndroidLibrary = "com.android.library"
    const val Hilt = "dagger.hilt.android.plugin"
    const val GoogleService = "com.google.gms.google-services"
    const val FirebaseCrash = "com.google.firebase.crashlytics"
    const val FirebasePerf = "com.google.firebase.firebase-perf"

    const val AndroidApp = "AndroidApp"
    const val AndroidCommonLibrary = "AndroidCommonLibrary"
    const val VersionCheck = "plugins.version-check"
    const val CodeQuality = "plugins.code-quality"
    const val GitHooks = "plugins.git-hooks"
    const val Ktlint = "plugins.ktlint"
    const val Spotless = "plugins.spotless"
    const val Detekt = "plugins.detekt"
    const val Dokka = "plugins.kdokka"
    const val TasksTest = "tasks.test-tasks"
}